apiVersion: apps/v1
kind: Deployment
metadata:
  name: karmada-controller-manager
  namespace: {{ karmada_namespace }}
  labels:
    app: karmada-controller-manager
spec:
  replicas: {{ controller_manager_size }}
  selector:
    matchLabels:
      app: karmada-controller-manager
  template:
    metadata:
      labels:
        app: karmada-controller-manager
    spec:
      serviceAccountName: karmada-controller-manager
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
      containers:
        - name: karmada-controller-manager
          image: {{ karmada_image_registry }}/karmada/karmada-controller-manager:{{ karmada_controller_manager_version }}
          imagePullPolicy: IfNotPresent
          command:
            - /bin/karmada-controller-manager
            - --kubeconfig=/etc/kubeconfig
            - --bind-address=0.0.0.0
            - --cluster-status-update-frequency=10s
            - --secure-port=10357
            - --feature-gates=PropagateDeps=true
            - --v=4
          volumeMounts:
          - name: kubeconfig
            subPath: kubeconfig
            mountPath: /etc/kubeconfig
      volumes:
        - name: kubeconfig
          secret:
            secretName: kubeconfig
