apiVersion: apps/v1
kind: Deployment
metadata:
  name: karmada-scheduler
  namespace: {{ karmada_namespace }}
  labels:
    app: karmada-scheduler
spec:
  replicas: {{ scheduler_size }}
  selector:
    matchLabels:
      app: karmada-scheduler
  template:
    metadata:
      labels:
        app: karmada-scheduler
    spec:
      serviceAccountName: karmada-scheduler
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
      containers:
        - name: karmada-scheduler
          image: {{ karmada_image_registry }}/karmada/karmada-scheduler:{{ karmada_scheduler_version }}
          imagePullPolicy: IfNotPresent
          command:
            - /bin/karmada-scheduler
            - --kubeconfig=/etc/kubeconfig
            - --bind-address=0.0.0.0
            - --secure-port=10351
            - --feature-gates=Failover=true
            - --enable-scheduler-estimator=true
            - --v=4
          volumeMounts:
            - name: kubeconfig
              subPath: kubeconfig
              mountPath: /etc/kubeconfig
      volumes:
        - name: kubeconfig
          secret:
            secretName: kubeconfig
