apiVersion: v1
stringData:
  kubeconfig: |-
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: {{ karmada_ca_crt_value }}
        server: https://karmada-apiserver.{{ karmada_namespace }}.svc.{{ cluster_domain }}:5443
      name: karmada-apiserver
    contexts:
    - context:
        cluster: karmada-apiserver
        user: karmada-apiserver
      name: karmada-apiserver
    current-context: karmada-apiserver
    kind: Config
    preferences: {}
    users:
    - name: karmada-apiserver
      user:
        client-certificate-data: {{ karmada_admin_crt_value }}
        client-key-data: {{ karmada_admin_key_value }}
kind: Secret
metadata:
  name: kubeconfig
  namespace: {{ karmada_namespace }}
