apiVersion: v1
kind: ServiceAccount
metadata:
  name: karmada-controller-manager
  namespace: {{ karmada_namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: karmada-scheduler
  namespace: {{ karmada_namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: karmada-webhook
  namespace: {{ karmada_namespace }}
