---
- name: Read Cert Files into variables
  set_fact:
    karmada_ca_crt_value: "{{ lookup('file', '{{ karmada_ca_crt_filename }}') | b64encode }}"
    karmada_ca_key_value: "{{ lookup('file', '{{ karmada_ca_key_filename }}') | b64encode }}"
    karmada_front_proxy_ca_crt_value: "{{ lookup('file', '{{ karmada_front_proxy_ca_crt_filename }}') | b64encode }}"
    karmada_front_proxy_ca_key_value: "{{ lookup('file', '{{ karmada_front_proxy_ca_key_filename }}') | b64encode }}"
    karmada_front_proxy_client_ca_crt_value: "{{ lookup('file', '{{ karmada_front_proxy_client_ca_crt_filename }}') | b64encode }}"
    karmada_front_proxy_client_ca_key_value: "{{ lookup('file', '{{ karmada_front_proxy_client_ca_key_filename }}') | b64encode }}"
    karmada_server_crt_value: "{{ lookup('file', '{{ karmada_server_crt_filename }}') | b64encode }}"
    karmada_server_key_value: "{{ lookup('file', '{{ karmada_server_key_filename }}') | b64encode }}"
    karmada_server_kubelet_client_crt_value: "{{ lookup('file', '{{ karmada_server_kubelet_client_crt_filename }}') | b64encode }}"
    karmada_server_kubelet_client_key_value: "{{ lookup('file', '{{ karmada_server_kubelet_client_key_filename }}') | b64encode }}"
    karmada_kube_controller_manager_crt_value: "{{ lookup('file', '{{ karmada_kube_controller_manager_crt_filename }}') | b64encode }}"
    karmada_kube_controller_manager_key_value: "{{ lookup('file', '{{ karmada_kube_controller_manager_key_filename }}') | b64encode }}"
    karmada_admin_crt_value: "{{ lookup('file', '{{ karmada_admin_crt_filename }}') | b64encode }}"
    karmada_admin_key_value: "{{ lookup('file', '{{ karmada_admin_key_filename }}') | b64encode }}"
    etcd_ca_crt_value: "{{ lookup('file', '{{ etcd_ca_crt_filename }}') | b64encode }}"
    etcd_client_crt_value: "{{ lookup('file', '{{ etcd_client_crt_filename }}') | b64encode }}"
    etcd_client_key_value: "{{ lookup('file', '{{ etcd_client_key_filename }}') | b64encode }}"
    "sa_key_value": "{{ lookup('file', '{{ karmada_sa_key_filename }}') | b64encode }}"
    "sa_pub_value": "{{ lookup('file', '{{ karmada_sa_pub_filename }}') | b64encode }}"



- name: Create Karmada TLS Secret
  k8s:
    state: "{{ state }}"
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ karmada_server_secret_name }}"
        namespace: "{{ karmada_namespace }}"
        labels:
          app: "{{ karmada_app_label }}"
          etcd_cluster: "{{ karmada_cluster_name }}"
      data:
        "ca.crt": "{{ karmada_ca_crt_value }}"
        "ca.key": "{{ karmada_ca_key_value }}"
        "front-proxy-ca.crt": "{{ karmada_front_proxy_ca_crt_value }}"
        "front-proxy-ca.key": "{{ karmada_front_proxy_ca_key_value }}"
        "front-proxy-client.crt": "{{ karmada_front_proxy_client_ca_crt_value }}"
        "front-proxy-client.key": "{{ karmada_front_proxy_client_ca_key_value }}"
        "server.crt": "{{ karmada_server_crt_value }}"
        "server.key": "{{ karmada_server_key_value }}"
        "apiserver-kubelet-client.crt": "{{ karmada_server_kubelet_client_crt_value }}"
        "apiserver-kubelet-client.key": "{{ karmada_server_kubelet_client_key_value }}"
        "kube-controller-manager.crt": "{{ karmada_kube_controller_manager_crt_value }}"
        "kube-controller-manager.key": "{{ karmada_kube_controller_manager_key_value }}"
        "admin.crt": "{{ karmada_admin_crt_value }}"
        "admin.key": "{{ karmada_admin_key_value }}"
        "etcd-ca.crt": "{{ etcd_ca_crt_value }}"
        "apiserver-etcd-client.crt" : "{{  etcd_client_crt_value }}"
        "apiserver-etcd-client.key": "{{  etcd_client_key_value }}"
        "sa.key": "{{ sa_key_value }}"
        "sa.pub": "{{ sa_pub_value }}"

- name: create karmada webhook cert secret
  k8s:
    state: "present"
    definition: "{{ lookup('template', 'karmada-webhook-cert-secret.yaml') | from_yaml }}"


- name: create karmada kubeconfig secret
  k8s:
    state: "present"
    definition: "{{ lookup('template', 'secret.yaml') | from_yaml }}"