apiVersion: install.karmada.io/v1alpha1
kind: KarmadaDeployment
metadata:
  name: demo-kmd
spec:
  mode: Helm
  controlPlane:
    etcd:
      storageMode: hostPath
    modules:
      - name: scheduler
        replicas: 2
        image: swr.ap-southeast-1.myhuaweicloud.com/karmada/karmada-scheduler:latest
      - name: controllerManager
        replicas: 2
        image: swr.ap-southeast-1.myhuaweicloud.com/karmada/karmada-controller-manager:latest
    # components:
    #   - search
    #   - descheduler
  images:
    karmadaRegistry: swr.ap-southeast-1.myhuaweicloud.com
    karmadaVersion: latest
    kubeRegistry: k8s-gcr.m.daocloud.io
    kubeVersion: "v1.24.2"
    dockerIoRegistry: docker.m.daocloud.io
