apiVersion: v1
kind: ServiceAccount
metadata:
  name: karmada-operator
  namespace: karmada-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: karmada-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: karmada-operator
  namespace: karmada-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: karmada-operator
  namespace: karmada-system
spec:
  selector:
    matchLabels:
      app: karmada-operator
  template:
    metadata:
      labels:
        app: karmada-operator
    spec:
      serviceAccountName: karmada-operator
      containers:
      - command:
        - /bin/karmada-operator
        - --v=4
        image: swr.ap-southeast-1.myhuaweicloud.com/karmada/karmada-operator
        imagePullPolicy: Always
        name: karmada-operator
